name = "251120"
spinup = 365 # days

[periods]
calibration = "kal"
validation = "val"
test = "test"

[path]
catchments = "settings/catchments/catchments_251120.txt"
parameter_ranges = "settings/parameter_ranges/parameter_ranges_251120.toml"
parameters_initial = "/hdata/hmdata01/DDD_calibration/BestPrimo2025/Best_par_{CATCHMENT}_3h_DDDv2.csv"
ptq = "/hdata/hmdata01/DDD_calibration/inndataV2/{CATCHMENT}/{CATCHMENT}_3h_ptq_SN2018_2209_{PERIOD}.csv"
output = "/hdata/hmdata01/DDD_calibration/output_251120/"
